### ISSUE TITLE
大佬，不支持V4镜像，需要格式化成tgbot格式

### ISSUE THREAD

**Issue by paopaoya** [qq34347476/js_script#10]
🔔获取互助码并格式化/docker自动更新容器下所有账号互助码, 开始!
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/jd/log/export_sharecodes'
    at Object.readdirSync (fs.js:1021:3)
    at Object.<anonymous> (/jd/scripts/format_share_jd_code.js:54:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/jd/log/export_sharecodes'
}

**Comment by qq34347476** [comment]
仓库有个单独的脚本，给机器人的
